[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
# Run migrations and then start the application
cmd = "sh -c 'python -m src migrate upgrade --revision head && python -m src monitor --skip-catchup'" 