[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m src"
healthcheckPath = "/"
healthcheckTimeout = 300

[database]
useConnectionString = true

# Explicitly set Nixpacks configuration
[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc"]

[phases.build]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "python -m src" 