[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m src"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"

[database]
useConnectionString = true 