[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
# Start the application without running migrations
startCommand = "python -m src monitor"
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckPort = 8080

[database]
useConnectionString = true

# Explicitly set Nixpacks configuration
[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc"]

[phases.build]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
# Start the application without running migrations
cmd = "python -m src monitor" 