"""remove_verified_and_deviation_fields

Revision ID: 09301bc066a2
Revises: fec343f2d3f9
Create Date: 2025-03-04 04:29:56.201581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09301bc066a2'
down_revision: Union[str, None] = 'fec343f2d3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
