"""Add count-based crash stats models

Revision ID: 9ec8942506c6
Revises: eef95128ad21
Create Date: 2025-03-04 12:35:11.698767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ec8942506c6'
down_revision: Union[str, None] = 'eef95128ad21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crash_stats', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('crash_stats', 'time_range',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=True,
               existing_server_default=sa.text("'daily'::character varying"))
    op.alter_column('crash_stats', 'games_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('crash_stats', 'average_crash',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('crash_stats', 'median_crash',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('crash_stats', 'max_crash',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('crash_stats', 'min_crash',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('crash_stats', 'standard_deviation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_unique_constraint('_date_timerange_uc', 'crash_stats', ['date', 'time_range'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_date_timerange_uc', 'crash_stats', type_='unique')
    op.alter_column('crash_stats', 'standard_deviation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('crash_stats', 'min_crash',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('crash_stats', 'max_crash',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('crash_stats', 'median_crash',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('crash_stats', 'average_crash',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('crash_stats', 'games_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('crash_stats', 'time_range',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'daily'::character varying"))
    op.alter_column('crash_stats', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
