"""remove_timestamp_metadata_from_crash_games

Revision ID: a677a46c451c
Revises: c955af91ef70
Create Date: 2025-03-04 15:44:01.985657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a677a46c451c'
down_revision: Union[str, None] = 'c955af91ef70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crash_games_created_at', table_name='crash_games')
    op.drop_column('crash_games', 'updated_at')
    op.drop_column('crash_games', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crash_games', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('crash_games', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_crash_games_created_at', 'crash_games', ['created_at'], unique=False)
    # ### end Alembic commands ###
