"""Add crashed_floor column

Revision ID: aaf46df36a0b
Revises: be71d7d70452
Create Date: 2025-03-04 06:52:08.640874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf46df36a0b'
down_revision: Union[str, None] = 'be71d7d70452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crash_games', sa.Column('crashed_floor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crash_games', 'crashed_floor')
    # ### end Alembic commands ###
