"""optimize_schema_remove_id_and_unix_fields

Revision ID: be71d7d70452
Revises: 09301bc066a2
Create Date: 2025-03-04 04:37:30.152192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be71d7d70452'
down_revision: Union[str, None] = '09301bc066a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crash_games', 'game_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('crash_games_game_id_key', 'crash_games', type_='unique')
    op.drop_column('crash_games', 'begin_time_unix')
    op.drop_column('crash_games', 'id')
    op.drop_column('crash_games', 'prepare_time_unix')
    op.drop_column('crash_games', 'end_time_unix')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crash_games', sa.Column('end_time_unix', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('crash_games', sa.Column('prepare_time_unix', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('crash_games', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('crash_games', sa.Column('begin_time_unix', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_unique_constraint('crash_games_game_id_key', 'crash_games', ['game_id'])
    op.alter_column('crash_games', 'game_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
