"""initial schema

Revision ID: bf0883b95827
Revises: 
Create Date: 2025-03-04 23:16:37.704849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0883b95827'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crash_games',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('hash_value', sa.String(), nullable=True),
    sa.Column('crash_point', sa.Float(), nullable=True),
    sa.Column('calculated_point', sa.Float(), nullable=True),
    sa.Column('crashed_floor', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('prepare_time', sa.DateTime(), nullable=True),
    sa.Column('begin_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index('ix_crash_games_begin_time', 'crash_games', ['begin_time'], unique=False)
    op.create_index('ix_crash_games_crash_point', 'crash_games', ['crash_point'], unique=False)
    op.create_index('ix_crash_games_end_time', 'crash_games', ['end_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crash_games_end_time', table_name='crash_games')
    op.drop_index('ix_crash_games_crash_point', table_name='crash_games')
    op.drop_index('ix_crash_games_begin_time', table_name='crash_games')
    op.drop_table('crash_games')
    # ### end Alembic commands ###
