"""Change float columns to numeric with 2 decimal precision

Revision ID: c5e0580ee7d2
Revises: 97d21cbb4197
Create Date: 2025-03-04 08:24:16.107484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e0580ee7d2'
down_revision: Union[str, None] = '97d21cbb4197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
