"""remove_stats_tables

Revision ID: c955af91ef70
Revises: 9ec8942506c6
Create Date: 2025-03-04 13:15:18.443487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c955af91ef70'
down_revision: Union[str, None] = '9ec8942506c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('count_based_crash_stats_reordered')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('count_based_crash_stats_reordered',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('end_game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('games_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_crash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('median_crash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('min_crash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_crash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('standard_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='count_based_crash_stats_reordered_pkey'),
    sa.UniqueConstraint('group_size', 'group_number', name='count_based_crash_stats_reordered_group_size_group_number_key')
    )
    # ### end Alembic commands ###
