"""Add time_range column to crash_stats table

Revision ID: eef95128ad21
Revises: c5e0580ee7d2
Create Date: 2025-03-04 08:50:30.036440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef95128ad21'
down_revision: Union[str, None] = 'c5e0580ee7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crash_stats', sa.Column('time_range', sa.String(length=20), nullable=True))
    op.drop_constraint('crash_stats_date_key', 'crash_stats', type_='unique')
    op.create_unique_constraint('_date_timerange_uc', 'crash_stats', ['date', 'time_range'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_date_timerange_uc', 'crash_stats', type_='unique')
    op.create_unique_constraint('crash_stats_date_key', 'crash_stats', ['date'])
    op.drop_column('crash_stats', 'time_range')
    # ### end Alembic commands ###
