"""init

Revision ID: fec343f2d3f9
Revises: 
Create Date: 2025-03-04 01:50:46.001976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fec343f2d3f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # First create the crash_games table
    op.create_table('crash_games',
                    sa.Column('game_id', sa.String(), nullable=False),
                    sa.Column('hash_value', sa.String(), nullable=True),
                    sa.Column('crash_point', sa.Float(), nullable=True),
                    sa.Column('calculated_point', sa.Float(), nullable=True),
                    sa.Column('end_time', sa.DateTime(), nullable=True),
                    sa.Column('prepare_time', sa.DateTime(), nullable=True),
                    sa.Column('begin_time', sa.DateTime(), nullable=True),
                    sa.Column('verified', sa.Boolean(),
                              server_default=sa.text('false'), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(precision=3),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        precision=3), nullable=True),
                    sa.PrimaryKeyConstraint('game_id')
                    )

    # Create crash_stats table
    op.create_table('crash_stats',
                    sa.Column('date', postgresql.TIMESTAMP(
                        precision=3), nullable=True),
                    sa.Column('games_count', sa.Integer(), nullable=True),
                    sa.Column('average_crash', sa.Float(), nullable=True),
                    sa.Column('median_crash', sa.Float(), nullable=True),
                    sa.Column('max_crash', sa.Float(), nullable=True),
                    sa.Column('min_crash', sa.Float(), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(precision=3),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        precision=3), nullable=True),
                    sa.PrimaryKeyConstraint('date')
                    )

    # Then, continue with the original operations (comments kept for reference only)
    # op.alter_column('crash_games', 'game_id',
    #           existing_type=sa.TEXT(),
    #           type_=sa.String(),
    #           nullable=True)
    # operations which are modifying existing columns are no longer needed
    # as we're creating the table with the correct schema

    # Create indexes
    op.create_index('ix_crash_games_begin_time', 'crash_games',
                    ['begin_time'], unique=False)
    op.create_index('ix_crash_games_crash_point',
                    'crash_games', ['crash_point'], unique=False)
    op.create_index('ix_crash_games_created_at', 'crash_games',
                    ['created_at'], unique=False)
    op.create_index('ix_crash_games_end_time', 'crash_games',
                    ['end_time'], unique=False)
    op.create_index('ix_crash_games_verified', 'crash_games',
                    ['verified'], unique=False)
    op.create_unique_constraint(None, 'crash_games', ['game_id'])
    op.create_unique_constraint(None, 'crash_stats', ['date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crash_stats', type_='unique')
    op.drop_constraint(None, 'crash_games', type_='unique')
    op.drop_index('ix_crash_games_verified', table_name='crash_games')
    op.drop_index('ix_crash_games_end_time', table_name='crash_games')
    op.drop_index('ix_crash_games_created_at', table_name='crash_games')
    op.drop_index('ix_crash_games_crash_point', table_name='crash_games')
    op.drop_index('ix_crash_games_begin_time', table_name='crash_games')

    # Drop the tables we created
    op.drop_table('crash_stats')
    op.drop_table('crash_games')
    # ### end Alembic commands ###
